ARG COREOS_VERSION="${COREOS_VERSION:-stable}"
ARG FEDORA_VERSION="${FEDORA_VERSION:-40}"
ARG IMAGE_REGISTRY="${IMAGE_REGISTRY:-ghcr.io/ublue-os}"
ARG KERNEL_FLAVOR="${KERNEL_FLAVOR:-coreos}"

# FROMs for copying
ARG KMOD_SRC="${IMAGE_REGISTRY}/ucore-kmods:${COREOS_VERSION}"
ARG KMOD_COMMON="${IMAGE_REGISTRY}/akmods:${KERNEL_FLAVOR}-${FEDORA_VERSION}"
ARG KMOD_NVIDIA="${IMAGE_REGISTRY}/akmods-nvidia:${KERNEL_FLAVOR}-${FEDORA_VERSION}"
FROM ${KMOD_SRC} AS ucore-kmods
FROM ${KMOD_COMMON} AS kmods-common
FROM ${KMOD_NVIDIA} AS kmods-nvidia

# image base
FROM quay.io/fedora/fedora-coreos:${COREOS_VERSION}

ARG COREOS_VERSION="${COREOS_VERSION:-stable}"
# build with --build-arg NVIDA_TAG="-nvidia" to install nvidia
ARG NVIDIA_TAG="${NVIDIA_TAG}"
# build with --build-arg ZFS_TAG="-zfs" to install zfs
ARG ZFS_TAG="${ZFS_TAG}"

COPY --from=ucore-kmods  /rpms/kmods/ublue*.rpm /tmp/rpms/
COPY --from=ucore-kmods  /rpms/kmods/nvidia/ublue*.rpm /tmp/rpms/nvidia/
COPY --from=kmods-nvidia /rpms/kmods/*.rpm /tmp/rpms/nvidia/
COPY --from=kmods-common /rpms/kmods/zfs/*.rpm /tmp/rpms/zfs/

COPY *.sh /tmp/

RUN mkdir -p /var/lib/alternatives \
    && /tmp/install.sh \
    && /tmp/post-install.sh \
    && mv /var/lib/alternatives /staged-alternatives \
    && rm -fr /tmp/* /var/* \
    && ostree container commit \
    && mkdir -p /var/lib && mv /staged-alternatives /var/lib/alternatives \
    && mkdir -p /tmp /var/tmp \
    && chmod -R 1777 /tmp /var/tmp