ARG COREOS_VERSION="${COREOS_VERSION:-stable}"

FROM quay.io/fedora/fedora-coreos:${COREOS_VERSION}

ARG COREOS_VERSION="${COREOS_VERSION:-stable}"
ARG IMAGE_NAME="${IMAGE_NAME:-ucore}"
ARG ADD_ZFS="${ADD_ZFS:-false}"

ADD github-release-install.sh /tmp/github-release-install.sh
ADD build.sh /tmp/build.sh
ADD post-install.sh /tmp/post-install.sh
ADD packages.json /tmp/packages.json

COPY --from=ghcr.io/ublue-os/ucore-kmods:${COREOS_VERSION} /rpms/ /tmp/rpms
COPY etc /etc
COPY usr /usr

# enable testing repos if not enabled on testing stream
RUN if [[ "testing" == "${COREOS_VERSION}" ]]; then \
for REPO in $(ls /etc/yum.repos.d/fedora-updates-testing{,-modular}.repo); do \
  if [[ "$(grep enabled=1 ${REPO} > /dev/null; echo $?)" == "1" ]]; then \
    echo "enabling $REPO" &&\
    sed -i '0,/enabled=0/{s/enabled=0/enabled=1/}' ${REPO}; \
  fi; \
done; \
fi

RUN if [[ "true" == "${ADD_ZFS}" ]]; then \
    rpm-ostree install /tmp/rpms/kmods/zfs/*.rpm; \
fi; \
    /tmp/github-release-install.sh trapexit/mergerfs x86_64.rpm fc && \
    /tmp/build.sh && \
    /tmp/post-install.sh && \
    rm -rf /tmp/* /var/* && \
    ostree container commit && \
    mkdir -p /var/tmp  && \
    chmod -R 1777 /var/tmp

COPY --from=docker.io/docker/compose-bin:latest /docker-compose /usr/bin/docker-compose