ARG COREOS_VERSION="${COREOS_VERSION:-stable}"

FROM quay.io/fedora/fedora-coreos:${COREOS_VERSION}

ARG COREOS_VERSION="${COREOS_VERSION:-stable}"

COPY --from=ghcr.io/ublue-os/ucore-kmods:${COREOS_VERSION} /rpms/ /tmp/rpms

# enable testing repos if not enabled on testing stream
RUN if [[ "testing" == "${COREOS_VERSION}" ]]; then \
for REPO in $(ls /etc/yum.repos.d/fedora-updates-testing{,-modular}.repo); do \
  if [[ "$(grep enabled=1 ${REPO} > /dev/null; echo $?)" == "1" ]]; then \
    echo "enabling $REPO" &&\
    sed -i '0,/enabled=0/{s/enabled=0/enabled=1/}' ${REPO}; \
  fi; \
done; \
fi

# install locally prepared RPMs (ZFS, etc)
RUN rpm-ostree install /tmp/rpms/kmods/zfs/*.rpm && \
    rpm-ostree cleanup -m && \
    rm -rf /tmp/* /var/* && \
    ostree container commit && \
    mkdir -p /var/tmp && \
    chmod -R 1777 /var/tmp