name: stable
on:
  merge_group:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '50 2 * * *'  # 2:50am-ish UTC everyday (approx 45 minutes after akmods images run)
  workflow_dispatch:

jobs:
  build-stable:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      coreos_version: stable
